### ISSUE TITLE
Pick up buttons don't seem to work

### ISSUE THREAD

**Issue by camtarn** [kikigame/Tinn#1]
Moved over a two-handed sword:

'Do you want to collect: 2-handed sword? [ Y: yes ] [ N: no ]'

Clicking the buttons does nothing, and removes focus from the input box, so that subsequently typing the letter Y does nothing.

Clicking to refocus the input then typing Y successfully picks up the sword.

**Comment by camtarn** [comment]
The same seems to happen with the Equip command.

In addition, when the buttons appear onscreen, input leaves the input box.

**Comment by kikigame** [comment]
The focus shouldn't leave the input box, and the buttons should send the "y" or "n" keypress to the server socket if clicked (and remove the y/n buttons).

I have tested this on Firefox/Linux and didn't see this issue, so it's almost certainly a browser compatibility problem.

Focus lost: This is probably a browser security feature on whichever browser you are using.

Buttons not working: The buttons use a onclick callback to invoke a javascript method call. So I'd expect clicking the buttons to work even if keyboard shortcuts failed. The fact that the buttons are created by JavaScript may be a factor (browser security).

Is there any chance of replicating the problem in a browser developer mode and posting the contents of the Javascript console?

**Comment by camtarn** [comment]
Doing so now.

I get this error message occasionally, but I don't think it's related, as
it doesn't happen on all loads:
Uncaught TypeError: Cannot read property 'type' of undefined
    at setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)
setFieldValue @ onloadwff.js:71
formKeydownListener @ onloadwff.js:71

Interestingly, the focus is now on the input box when I load the game.

The buttons still don't work, but I have no error messages in the console.
However, digging into the source, I noticed that line 115 (
btn.onclick='javascript:dialogResult('
+ key.trim() + ")"; ) doesn't seem to have any effect in Chrome: the button
DOM element never gains an onclick DOM attribute, nor an onclick JS
property.

I think the reason is given here:
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Event_handlers#HTML_onevent_attributes


"When the element is built from the HTML, the value of its onevent
attributes are copied to the DOM object that represents the element, so
that accessing the attributes' values using JavaScript will get the value
set in the HTML. *However*, this is a one-time thing. From that point on,
making changes to the JavaScript property has no effect on the HTML
attribute's value."

I'm guessing FF/Linux sneakily disregards this, and does as the author
intends, whereas Chrome/Win ignores all sets to that variable after the DOM
element is created.

The workaround is to set the DOM attribute itself:

btn.setAttribute('onclick', 'javascript:dialogResult("' + key.trim() + '")')

setAttribute dates back to IE5, so if you're targeting browsers any earlier
than this (...have fun!) you'd need to check for its existence before using
it.

There's a secondary bug in that line: you've got some missing quotes around
the string coming from the key - it evaluates
to 'javascript:dialogResult(Y)', whereas you
want 'javascript:dialogResult("Y")'. I've added the extra quotes above. I'm
quite surprised this works in FF/Linux, as it should generate an error ('
"Y" is undefined') in any modern browser.

For interest, using a string as an event handler is a *very* old way of
handling events. The more modern way of binding event handlers would look
like this (for functions with a single argument):

function bindClick( domElement, fn, arg ) {
  domElement.addEventListener( 'click', function() { fn( arg ); } );
}

function dialog( msg, opts, help ) {
  ...
    bindClick ( btn, dialogResult, key.trim() );
  ...
}

but I don't think there's any need to use that when the above way works
just fine with less lines :)

Cheers,
Andy

**Comment by kikigame** [comment]
Thank you; that's really helpful.

Focus on the input box was fixed last night; it was a minimised attribute in the XHTML that some browsers ignored.

FYI, onloadwff.js seems to be related to the LastPass extension, and is nothing to do with Tinn Cant, which doesn't even use passwords.

I'm still unsure about the focus issue when the "dialog" buttons disappear, but the onclick handler fix is now live and if it works for you I'll push it to github tonight.

**Comment by camtarn** [comment]
You have a missing ) at the end of line 116 :)

Also, that is pretty amusing about the onloadwff.js. I guess that explains why it only happened half the time.

As for the focus issue: you could just have a document.getElementById('i').focus(); at the end of dialogResult(). The focus will have moved to the button when clicking it, so it seems reasonable that it shouldn't automatically move back to the input box afterwards.

**Comment by kikigame** [comment]
Sorry; I really should test things before putting them online. Missing closing parenthesis is now restored.
I've also added the explicit focus() as you suggest.

**Comment by camtarn** [comment]
Tested it out, and it works for me.
