### ISSUE TITLE
Clarification: ranged weaponry

### ISSUE THREAD

**Issue by camtarn** [kikigame/Tinn#11]
I have a sling ... how do I use it? I can't 'use' the sling, nor 'use' a rock, as they both return 'That doesn't seem to work.'. Wielding the rock doesn't seem to make a difference, and there's no 'throw' or 'fire' verb that I can find. I seem to be able to use the sling as a melee weapon, but that doesn't consume rocks...

**Comment by kikigame** [comment]
Equip the sling as a weapon then use the rock to fire.
This is documented in the encyclopedia entry and mouseover description for the sling.

Note that the "use" action only works with missiles (including rocks) where there is a viable target in line of sight. A viable target is currently a monster that is neither co-aligned with you nor your species nor putting you under a magical charm.

**Comment by camtarn** [comment]
I can't reproduce the "That doesn't seem to work" with the rock any more, even after dropping/picking up/re-equipping the sling, so that seems like it works correctly.

How does one access the encyclopedia?

**Comment by kikigame** [comment]
The encyclopedia is currently only accessible by the in-game item, the "Hitch-Hiker's Guide". This is starting equipment for the Shopkeeper role.

**Comment by kikigame** [comment]
"That doesn't seem to work" is the message given when trying to use an item either where the item is not usable, or where the usage fails. In the case of a rock (or other missile weapon), the usage will fail if you have no viable target in line of sight.

**Comment by camtarn** [comment]
Ah-hah, that makes sense (both of the things).

I would suggest that using the sling ask you to use a suitable projectile
instead; and that projectiles have a better error message when they can't
be used for throwing (Perhaps difficult if some projectiles can be used for
multiple things?)
