### ISSUE TITLE
Game gives no feedback for non-forced movement into a Spring

### ISSUE THREAD

**Issue by camtarn** [kikigame/Tinn#2]
Attempting to move into a Spring doesn't seem to work, but the game doesn't print out any message informing you of that.

Forced movement works.

**Comment by kikigame** [comment]
Springboards are a kind of trap, and you can't move onto a trap without the "force" action (that's what "force" does). So in that sense, it's not a bug.

But it agree that there should be a message, probably not a y/n prompt, to indicate why you can't move.

**Comment by kikigame** [comment]
Implemented & on github; will be in the next binary build for the backend.
