### ISSUE TITLE
When I die, the game process cuts me off...?

### ISSUE THREAD

**Issue by camtarn** [kikigame/Tinn#9]
I'm trying out leaving all my equipment behind, and wandering around while monsters attack me.

After a few turns of combat, the Tinn server process stops returning any data, but it doesn't show my last round of combat or any death message.

**Comment by kikigame** [comment]
When I die through the web interface, I get a popup dialog saying "You are no longer alive". The text area shows the attack and then the "shall we play a game" prompt occurs again (spawning a new session).

The backend sends another closing message to the fifo but then exits, so the CGI tidies the session, deleting the fifo without reading it (we need to keep that behaviour at least in the case where the game crashes). It's the only circumstance where no <!OVER!> message is sent.

The only fix I can see is to add a formal closing handshake. Tinn would send "<!FIN!>" to Cant, and Cant would then send a "<!FIN!>" back to Tinn. Tinn thus waits for input before exiting (so crash clean-up isn't invoked) and Cant would be able to read and handle all messages before identifying the shutdown (perhaps by redirecting to the front page).

This means changes to src/output_fifo.cpp and cant/index.pl.

**Comment by kikigame** [comment]
I've pushed live a new update with a build including this handshaking (and other fixes).

Unfortunately, it's still not working as I expected, so something else is losing the closing messages at the end of the game.

However, the game will now tell you "Thanks for playing" to indicate the game is over, which is an incremental improvement.

**Comment by kikigame** [comment]
fifio_ios::~fifo_ios needed to flush the buffer before exiting.
Now fixed; pushed to github and live.
